server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///plandemo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1
      validation-query-timeout: 2000
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 1000
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
pagehelper:
  reasonable: false
  support-methods-arguments: true
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage:  cn.shuhan.plan.domain.entity
